const ActionTypes = {
    SIGNUP_USER_SUCCESS : 'SIGNUP_USER_SUCCESS',
    LOGIN_USER_SUCCESS : 'LOGIN_USER_SUCCESS',
    FILL_USER_PLAYLISTS : 'FILL_USER_PLAYLISTS',
    UPDATE_USER_PLAYLISTS : 'UPDATE_USER_PLAYLISTS',
    CLEAR_USER : 'CLEAR_USER',
    CLEAR_PLAYLISTS : 'CLEAR_PLAYLISTS',
}

export default ActionTypes